version: "3.8"

services:
    authentication:
        image: "nginx:stable-alpine"
        container_name: auth_server
        ports:
            - 7000:80
        volumes:
            - ./:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
            - mysql
        networks:
            - auth

    php:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
        container_name: auth_php
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - auth

    mysql:
        image: mysql:5.7.22
        container_name: auth_mysql
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        restart: unless-stopped
        ports:
            - 55066:3306
        networks:
            - auth

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - auth

networks:
    auth:
        driver: bridge
